tts: add e.g. with fastspeech2 and wavegrad
mindspore-lab/mindaudio pull request #170
Opened 2023-06-25 09:21 UTC by DongyaoZhu

2023-06-25 14:02 UTC, vigo999 commented on examples/fastspeech2/README.md
> +MindSpore implementation of [FastSpeech2](https://arxiv.org/abs/2006.04558), a text-to-melspectrogram model for text-to-speech systems.
remove MindSpore implementation of

2023-06-25 14:03 UTC, vigo999 commented on examples/fastspeech2/README.md
> +`python recipes/LJSpeech/tts/fastspeech2/generate.py --restore fastspeech2_160k_en_mel128.ckpt --text "hello this is a test sentence"`
please correct scripts path

2023-06-25 14:05 UTC, vigo999 commented on examples/fastspeech2/README.md
> +python recipes/LJSpeech/tts/fastspeech2/preprocess.py
please correct scripts path

2023-06-25 14:05 UTC, vigo999 commented on examples/fastspeech2/README.md
> +Other training and model parameters can be set in `recipes/LJSpeech/tts/fastspeech2/fastspeech2.yaml`.
please correct scripts path

2023-06-25 14:09 UTC, vigo999 commented on examples/fastspeech2/README.md
> +export MY_DEVICE=Ascend # options: [Ascend, GPU]
remove this setting. 
user can set target device via train.py args

2023-06-25 14:09 UTC, vigo999 commented on examples/fastspeech2/README.md
> +nohup python train.py --device_target $MY_DEVICE > train_single.log &
remove nohup and log info.
python train.py --device_target Ascend

2023-06-25 14:10 UTC, vigo999 commented on examples/fastspeech2/README.md
> +- [MindAudio](https://github.com/mindspore-lab/mindaudio)
remove mindaudio ref

2023-06-25 14:22 UTC, vigo999 commented on examples/fastspeech2/fastspeech2.yaml
> +lexicon_path: 'recipes/text/librispeech-lexicon.txt'
please upload lexicon txt to examples/fastspeech2 folder and correct this path

2023-06-25 14:25 UTC, vigo999 commented on examples/fastspeech2/generate.py
> +    hps = mindaudio.load_config(args.config)
mindaudio load config function has been removed. please upload this scripts to examples/config.py

from pprint import pformat
import numpy as np
import yaml

class Config:
    def __init__(self, cfg_dict):
        for k, v in cfg_dict.items():
            if isinstance(v, (list, tuple)):
                setattr(self, k, [Config(x) if isinstance(x, dict) else x for x in v])
            else:
                setattr(self, k, Config(v) if isinstance(v, dict) else v)

    def __str__(self):
        return pformat(self.__dict__)

    def __repr__(self):
        return self.__str__()


def load_config(path):
    with open(path) as stream:
        hps = yaml.load(stream, yaml.Loader)
    hps = Config(hps)
    return hps

2023-06-25 14:27 UTC, vigo999 commented on examples/fastspeech2/generate.py
> +    model, _ = mindaudio.create_model("FastSpeech2", hps, args.restore, is_train=False)
please create fastspeech2 model step by step not using create_model api since this api has been removed for some reason.

2023-06-25 14:29 UTC, vigo999 commented on examples/fastspeech2/preprocess.py
> +hps = mindaudio.load_config(args.config)
same as above load config function. please upload your config.py to examples/fastspeech2

2023-06-25 14:33 UTC, vigo999 commented on examples/fastspeech2/train.py
> +    hps = mindaudio.load_config(args.config)
same problem as above load config

2023-06-25 14:34 UTC, vigo999 commented on examples/fastspeech2/train.py
> +    model, ckpt = mindaudio.create_model(
same problem as above for create_model apio

2023-06-25 14:35 UTC, vigo999 commented on examples/wavegrad/reverse.py
> +model, ckpt = mindaudio.create_model("WaveGrad", hps, args.restore, is_train=False)
same problem as fastspeech2. please create model step by step with create_model api

2023-06-25 14:36 UTC, vigo999 commented on examples/wavegrad/README.md
> +MindSpore implementation of [WaveGrad](https://arxiv.org/abs/2009.00713), a diffusion based vocoder model for text-to-speech systems.
remove 'MindSpore implementation of '

2023-06-25 14:36 UTC, vigo999 commented on examples/wavegrad/README.md
> +`python recipes/LJSpeech/tts/wavegrad/reverse.py --restore model_1000000.ckpt --wav LJ010-0142.wav --save results --device_target Ascend --device_id 0 --plot`
please correct scripts path

2023-06-25 14:36 UTC, vigo999 commented on examples/wavegrad/README.md
> +`python recipes/LJSpeech/tts/wavegrad/reverse.py --restore model_1000000.ckpt --mel fs.npy --save results --device_target Ascend --device_id 0 --plot`
scripts path problem

2023-06-25 14:37 UTC, vigo999 commented on examples/wavegrad/README.md
> +export MY_DEVICE=Ascend # options: [Ascend, GPU]
remove MY_DEVICE setting. 
set target device via train.py scripts.

2023-06-25 14:41 UTC, vigo999 commented on examples/wavegrad/README.md
> +nohup mpirun --allow-run-as-root -n $MY_DEVICE_NUM python recipes/LJSpeech/tts/wavegrad/train.py --device_target $MY_DEVICE --is_distributed True --context_mode graph > train_distributed.log &
please correct it as belows:
mpirun --allow-run-as-root -n 8 python train.py --device_target Ascend --is_distributed True --context_mode graph

2023-06-25 14:42 UTC, vigo999 commented on examples/wavegrad/README.md
> +nohup python train.py --device_target $MY_DEVICE --context_mode graph > train_single.log &
please correct it as below:
python train.py --device_target Ascend --context_mode graph

2023-06-25 14:45 UTC, vigo999 commented on examples/wavegrad/README.md
> +- [youtube](https://www.youtube.com/watch?v=nv-WTeKRLl0)
please fill in [] with video title 
[Learning to Generate Data by Estimating Gradients of the Data Distribution (Yang Song, Stanford)]
ps: this video is for diffusion?? just double confirm

2023-06-25 14:45 UTC, vigo999 commented on examples/wavegrad/README.md
> +- [MindAudio](https://github.com/mindspore-lab/mindaudio)
remove mindaudio ref

2023-06-25 14:46 UTC, vigo999 commented on examples/wavegrad/README.md
> +Computational Resources:
remove computational resources.

2023-06-25 14:46 UTC, vigo999 commented on examples/wavegrad/preprocess.py
> +    hps = mindaudio.load_config(args.config)
same problem as above 'load config'

2023-06-25 14:47 UTC, vigo999 commented on examples/wavegrad/reverse.py
> +        default="recipes/LJSpeech/tts/wavegrad/wavegrad_base.yaml",
correct default config path to examples/xxx

2023-06-25 14:47 UTC, vigo999 commented on examples/wavegrad/reverse.py
> +hps = mindaudio.load_config(args.config)
'load config ' problem

2023-06-25 14:48 UTC, vigo999 commented on examples/wavegrad/reverse.py
> +model, ckpt = mindaudio.create_model("WaveGrad", hps, args.restore, is_train=False)
same problem as 'create_model' api

2023-06-25 14:48 UTC, vigo999 commented on examples/wavegrad/train.py
> +        default="recipes/LJSpeech/tts/wavegrad/wavegrad_base.yaml",
correct default config path

2023-06-25 14:49 UTC, vigo999 commented on examples/wavegrad/train.py
> +    hps = mindaudio.load_config(args.config)
'load config ' problem

2023-06-25 14:49 UTC, vigo999 commented on examples/wavegrad/train.py
> +    wavegrad, ckpt = mindaudio.create_model(
'create_model' problem

2023-06-25 14:51 UTC, vigo999 requested changes
please check comments

2023-06-28 14:43 UTC, vigo999 approved these changes

2023-06-28 14:50 UTC, vigo999 commented
pre-commit @DongyaoZhu

2023-06-30 02:15 UTC, LiTingyu1997 approved these changes

2023-06-30 11:58 UTC, closed without merging